title: Learning GitHub Pages
author: Me
email: me@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just ignore this description

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
